name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build and commit the PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compile resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: View logs
        run: cat main.log

      - name: Move PDF
        run: |
          mkdir build
          mv main.pdf 'build/pratyay_resume.pdf'

      - name: Push build
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
